{
 "title": "result",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Mức tồn kho ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "inventory_stock_level{sku=\"NIK1-WHITE-38\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Real-time Order Throughput (Req/s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{uri=~\"/api/cart/checkout.*\"}[5s]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Tỷ lệ Đặt hàng",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (status) (orders_processed_total)",
     "legendFormat": "__auto"
    },
    {}
   ]
  }
 ]
}